# Generated by Django 5.1.1 on 2024-10-05 00:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Summary')], max_length=10)),
                ('date_range', models.JSONField()),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login Attempt'), ('FIREWALL', 'Firewall Event'), ('IDS', 'Intrusion Detection'), ('MALWARE', 'Malware Detection'), ('FORWARD', 'Forwarded Event'), ('DNS', 'DNS Event'), ('DHCP', 'DHCP Event'), ('AUTH', 'Authentication Event'), ('VPN', 'VPN Event'), ('TIMESYNC', 'Time Synchronization'), ('SYSTEM', 'System Event')], max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('description', models.TextField()),
                ('raw_data', models.JSONField()),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField()),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('security_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='data_processing.securityevent')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('dimension', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('metric_name', 'start_time', 'end_time', 'dimension')},
            },
        ),
    ]
